config/routes.rb
Rails.application.routes.draw do
  resources :tweets do 
    # member do
    #   post :retweet
    # end
    resources :retweets
  end
   get '/search' => 'tweets#search'
  devise_for :users
  root to: "tweets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :tweet


  def user_name
    if self.user_id.present?
      @user = User.find_by(id: self.user_id)
      @user.email
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :retweets
  belongs_to :tweet, optional: true

  def tweet_type
    if tweet_id? && description?
      "quote-tweet"
    elsif tweet_id?
      "retweet"
    else
      "tweet"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
	before_action :set_tweet

	def create
		@comment = @tweet.retweets.new(retweet_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to @tweet
		end
	end	

	private
	 def retweet_params
	 	params.require(:retweet).permit(:content, :user_id, :tweet_id)
	 end

	def set_tweet
		@tweet = Tweet.find(params[:tweet_id])
	end	
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    
    if params[:search].present?
      @tweets = Tweet.where("title like :search or description like :search",{search: "%#{params[:search]}%"})
    else
      @tweets = Tweet.all
    end

  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end


  def retweet
    @tweet = Tweet.find(params[:id])
    retweet = current_user.tweets.new(tweet_id: @tweet.id)
    if retweet.save
      redirect_to tweets_path
    else
      redirect_to :back, alert: "Unable to retweet"
    end
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:title, :description, :user_id, :tweet_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterCloneApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><a class="active" href="/">Home</a></li>
      <li>
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path(current_user), method: :get %>
        <%else%>
          <%= link_to "Sign in", new_user_session_path%>
        <%end%>
      </li>
      <li style="float: right;"><p class="name"><%= "Log in user:-#{current_user.email}" if user_signed_in?%></p></li>
    </ul>
    <div class="main_body">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/retweets/_new.html.erb
<%= form_with model: [ @tweet, Retweet.new ] do |form| %>
 Your comment:<br>
 <%= form.text_area :content, size: "20*5" %>
 <br>
 <%= form.submit "Retweet" %>
<% end %> 
<br>

app/views/retweets/_retweet.html.erb
<div id="<%= dom_id(retweet)%>">
	<b>Posted By:- </b><%= retweet.user_name%>
	<br>
	<b>Retweet:- </b><%= retweet.content%>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<% end %>

app/views/tweets/_retwetting.html.erb
<div id="retweet">
	<%= render tweet.retweets %>
</div>

<%if user_signed_in? && tweet.user_id != current_user.id%>
<%= render "retweets/new", tweet: tweet %>
<%end%>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="show_flex">
  <div style="width:50%">
    <%= form_tag(tweets_path, :method => "get") do%>
      <%= search_field_tag :search, params[:search], class: "search"%>
      <%= button_tag "search", class: "blue"%>
    <%end%>
  </div>
  <div  style="width:50%; text-align:right">
    <% if user_signed_in? %>
      <%= link_to "New Tweet", new_tweet_path, class: "blue"%>
    <%end%>
  </div>
</div>

<br>
<h1 class="center">List of All Tweets</h1>
 <hr>
<div class="index_page">
<% @tweets.each do |tweet| %>
  <div class="blog">
    <%#= render partial: "tweets/#{tweet.tweet_type}", locals: {tweet: tweet} %>
   
    <h2>Tweet Title:-</h2> <%= tweet.title %><br>
    <h2>Tweet Description :- </h2>  <%= tweet.description %>
    <br>
    <%= link_to 'Show', tweet , class: "button"%>
    <hr>
<% end %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path ,class: "blue"%>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><strong>Title:</strong></h1>
  <%= @tweet.title %>
</p>

<p>
  <h1><strong>Description:</strong></h1>
  <%= @tweet.description %>
</p>



<%= render "tweets/retwetting", tweet: @tweet %>

<%= link_to 'Edit', edit_tweet_path(@tweet), class: "blue" if @tweet.user_id == current_user.id%> 

<%= link_to 'Back', tweets_path , class: "red"%>